create table notification
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    created_by varchar(255),
    updated_at timestamp(6) with time zone,
    updated_by varchar(255)
);

alter table notification
    owner to routex;

